### ISSUE TITLE
Feature request: Automatic dark mode

### ISSUE THREAD

**Issue by igorkulman** [Swetrix/swetrix-fe#35] opened 2022-04-24 17:05 UTC
It would be nice to automatically switch between dark and light mode instead of having to click the button.

**Comment by Blaumaus** [comment] 2022-04-25 14:11
The frontend already uses operating system prefered theme as the default value (see [here](https://github.com/Swetrix/swetrix-fe/blob/main/src/redux/reducers/ui/theme.js#L11)).
It stores this value into the local storage, so when user changes the prefered colour theme in the OS settings, it will be ignored next time they visit the website.

This is not the intended behaviour and will be fixed soon, thanks for reporting it!

**Comment by Blaumaus** [comment] 2022-04-25 20:13
Has been fixed in https://github.com/Swetrix/swetrix-fe/commit/3e2799db093ea975abc1d9f5e2d7a72bd2123e73.
Now unless user clicks on the theme switch button, it won't be stored in the Local Storage.

**Closed by Blaumaus** 2022-04-25 20:13 UTC
